### ISSUE TITLE
How to use ckeditor-mathml in toolbar

### ISSUE THREAD

**Issue by rathiayush** [wiris/ckeditor5-mathml#2]
I have installed
npm install @wiris/ckeditor5-mathml

Update the CKEditor configuration by adding the plugin:

import MathML from '@wiris/ckeditor5-mathml/src/mathml';

ClassicEditor
     .create( editorElement, {
         plugins: [ ..., MathML, ... ],

but its showing nothing on ckeditor5 toolbar. Could you please update readme for what needs to be added in ckeditor5 config in order to see it on toolbar for eg:-

`ClassicEditor.defaultConfig = {
	toolbar: {
		items: [
			'removeFormat',
			'bold',
			'Italic',
			'Underline',
		]
	}}`

**Comment by mcagigas-at-wiris** [comment]
Hi @rathiayush 

This plugins extends the CKEditor 5 model to allow working with the MathML standard. This means that you can work with MathML in CKEditor5. However this plugin doesn't provide a way to create MathML formulas. 

You can try the plugin https://www.npmjs.com/package/@wiris/mathtype-ckeditor5 which adds MathType editor to CKEditor5. 

Best,

**Comment by rathiayush** [comment]
Hello @manuelwiris ,
Thanks for quick response.
but [mathtype-ckeditor5](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5) has some issues which is breaking ckeditor5.
please see below thread:-
[Mathtype-ckeditor5 editor.setData() issue](https://github.com/ckeditor/ckeditor5/issues/1920)

**Comment by rathiayush** [comment]
> Hello @manuelwiris ,
> Thanks for quick response.
> but [mathtype-ckeditor5](https://www.npmjs.com/package/@wiris/mathtype-ckeditor5) has some issues which is breaking ckeditor5.
> please see below thread:-
> [Mathtype-ckeditor5 editor.setData() issue](https://github.com/ckeditor/ckeditor5/issues/1920)

@manuelwiris could you please have look

**Comment by mcagigas-at-wiris** [comment]
@rathiayush 

Last week we release a new version of the plugin which solves the issues you mentioned. 

Best,
